<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->insert([
            // HYGIENE------------------------- -----------------------------------------------
            [
                'name'=>'Wave Air Freshner',
                'price'=>'210',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti tobacco',
                'gallery'=>'/images/hy1.jpg',
            ],
            [
                'name'=>'KN 95',
                'price'=>'40',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti Corona',
                'gallery'=>'\images\hy2.PNG',
            ],
            [
                'name'=>'Savlon Pro',
                'price'=>'200',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Best daily life cleaner',
                'gallery'=>'/images/hy3.jpg',
            ],
            // TREE------------------------- -----------------------------------------------
            [
                'name'=>'Bonzai',
                'price'=>'1500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr1.jpg',
            ],
            [
                'name'=>'Bonzai Lumb',
                'price'=>'700',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr2.jpg',
            ],
            [
                'name'=>'Cactus Gold',
                'price'=>'400',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr3.jpg',
            ],
            [
                'name'=>'Mini Cactus',
                'price'=>'500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr4.jpg',
            ],
            [
                'name'=>'Monstera',
                'price'=>'900',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr5.jpg',
            ],
            // Furnitures ------------------------- -----------------------------------------------
            [
                'name'=>'Dark Tul',
                'price'=>'1300',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f1.jpg',
            ],
            [
                'name'=>'Sofa Set',
                'price'=>'20000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f2.jpg',
            ],
            [
                'name'=>'Green Sofa',
                'price'=>'15000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f3.jpg',
            ],
            [
                'name'=>'Pinkish',
                'price'=>'2000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f4.jpg',
            ],
            [
                'name'=>'Desk Chair',
                'price'=>'5000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f5.jpg',
            ],
            //DIAPERS-----------------------------------------------------------------------------
            [
                'name'=>'Molfix',
                'price'=>'500',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 12 piece',
                'gallery'=>'/images/d1.jpg',
            ],
            [
                'name'=>'Huggies',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 32 piece',
                'gallery'=>'/images/d2.jpg',
            ],
            [
                'name'=>'Supermom',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 22 piece',
                'gallery'=>'/images/d3.jpg',
            ],
            [
                'name'=>'Avonee',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 10 piece',
                'gallery'=>'/images/d4.jpg',
            ],
            //FEEDER-----------------------------------------------------------------------------
            [
                'name'=>'Feeder 1.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe1.jpg',
            ],
            [
                'name'=>'Feeder 2.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe2.jpg',
            ],
            [
                'name'=>'Feeder 3.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe3.jpg',
            ],
            //MEAT-----------------------------------------------------------------------------

            [
                'name'=>'Mutton',
                'price'=>'800',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m1.jpg',
            ],
            [
                'name'=>'Chicken',
                'price'=>'200',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m2.jpg',
            ],
            //BEVERAGES-----------------------------------------------------------------------------
            [
                'name'=>'Nescafe',
                'price'=>'250',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Cafane will reduce your stress. ',
                'gallery'=>'/images/be1.jpg',
            ],
            [
                'name'=>'Kool',
                'price'=>'50',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Amul Kool is Now in Bangladesh. ',
                'gallery'=>'/images/be2.jpg',
            ],
            [
                'name'=>'Tang',
                'price'=>'950',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Original mango flavour. ',
                'gallery'=>'/images/be3.jpg',
            ],
            [
                'name'=>'Roof Afza',
                'price'=>'110',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'From Pakistan. ',
                'gallery'=>'/images/be4.jpg',
            ],
            [
                'name'=>'TRU',
                'price'=>'750',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Have every drop in soul with TRU. ',
                'gallery'=>'/images/be5.jpg',
            ],
            [
                'name'=>'Mr Twist',
                'price'=>'10',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Feel the notalgic. ',
                'gallery'=>'/images/be6.jpg',
            ],
            //CHLOTH-----------------------------------------------------------------------------
            [
                'name'=>'Gucci',
                'price'=>'150',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment.jpg',
            ],
            [
                'name'=>'Lose Pants',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp1.jpg',
            ],
            [
                'name'=>'Jacket',
                'price'=>'800',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment1.jpg',
            ],
            [
                'name'=>'Trouser',
                'price'=>'400',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp2.jpg',
            ],
            [
                'name'=>'DHAKA',
                'price'=>'100',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment2.jpg',
            ],
            [
                'name'=>'Denim',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment3.jpg',
            ],
            //SHOE -----------------------------------------------------------------------------
            [
                'name'=>'Shoe',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens1.jpeg',
            ],
            [
                'name'=>'Snecker',
                'price'=>'1800',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens2.jpg',
            ],
            [
                'name'=>'Sandle',
                'price'=>'3200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens3.jpg',
            ],
            //WOMEN TOP-----------------------------------------------------------------------------
            [
                'name'=>'Velvet Top',
                'price'=>'900',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt1.jpg',
            ],
            [
                'name'=>'Blue Top',
                'price'=>'700',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt2.jpg',
            ],
            [
                'name'=>'Velvet Top',
                'price'=>'500',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt3.jpg',
            ],
            //WOMEN HEEL-----------------------------------------------------------------------------
            [
                'name'=>'Pink Heel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel1.jpg',
            ],
            [
                'name'=>'Red Heel',
                'price'=>'5000',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel2.jpg',
            ],
            [
                'name'=>'Flat Sandel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel3.jpg',
            ],
            //BEAUTY-----------------------------------------------------------------------------
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b1.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b2.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b3.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b4.jpg',
            ],
            //Accessories-----------------------------------------------------------------------------
            [
                'name'=>'Guess (Gold Edition)',
                'price'=>'15000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a1.jpg',
            ],
            [
                'name'=>'Lather Walted',
                'price'=>'500',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a2.jpg',
            ],
            [
                'name'=>'Gucci Leo Ring',
                'price'=>'1000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Gucci limited edition grab yours now. ',
                'gallery'=>'/images/a3.jpg',
            ],
            [
                'name'=>'Side bag',
                'price'=>'670',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Strong side bag for daily work. ',
                'gallery'=>'/images/a4.jpg',
            ],
            [
                'name'=>'Grass necklace',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This necklace will enhance your look. ',
                'gallery'=>'/images/a5.jpg',
            ],// HYGIENE------------------------- -----------------------------------------------
            [
                'name'=>'Wave Air Freshner',
                'price'=>'210',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti tobacco',
                'gallery'=>'/images/hy1.jpg',
            ],
            [
                'name'=>'KN 95',
                'price'=>'40',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti Corona',
                'gallery'=>'\images\hy2.PNG',
            ],
            [
                'name'=>'Savlon Pro',
                'price'=>'200',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Best daily life cleaner',
                'gallery'=>'/images/hy3.jpg',
            ],
            // TREE------------------------- -----------------------------------------------
            [
                'name'=>'Bonzai',
                'price'=>'1500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr1.jpg',
            ],
            [
                'name'=>'Bonzai Lumb',
                'price'=>'700',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr2.jpg',
            ],
            [
                'name'=>'Cactus Gold',
                'price'=>'400',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr3.jpg',
            ],
            [
                'name'=>'Mini Cactus',
                'price'=>'500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr4.jpg',
            ],
            [
                'name'=>'Monstera',
                'price'=>'900',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr5.jpg',
            ],
            // Furnitures ------------------------- -----------------------------------------------
            [
                'name'=>'Dark Tul',
                'price'=>'1300',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f1.jpg',
            ],
            [
                'name'=>'Sofa Set',
                'price'=>'20000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f2.jpg',
            ],
            [
                'name'=>'Green Sofa',
                'price'=>'15000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f3.jpg',
            ],
            [
                'name'=>'Pinkish',
                'price'=>'2000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f4.jpg',
            ],
            [
                'name'=>'Desk Chair',
                'price'=>'5000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f5.jpg',
            ],
            //DIAPERS-----------------------------------------------------------------------------
            [
                'name'=>'Molfix',
                'price'=>'500',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 12 piece',
                'gallery'=>'/images/d1.jpg',
            ],
            [
                'name'=>'Huggies',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 32 piece',
                'gallery'=>'/images/d2.jpg',
            ],
            [
                'name'=>'Supermom',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 22 piece',
                'gallery'=>'/images/d3.jpg',
            ],
            [
                'name'=>'Avonee',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 10 piece',
                'gallery'=>'/images/d4.jpg',
            ],
            //FEEDER-----------------------------------------------------------------------------
            [
                'name'=>'Feeder 1.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe1.jpg',
            ],
            [
                'name'=>'Feeder 2.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe2.jpg',
            ],
            [
                'name'=>'Feeder 3.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe3.jpg',
            ],
            //MEAT-----------------------------------------------------------------------------

            [
                'name'=>'Mutton',
                'price'=>'800',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m1.jpg',
            ],
            [
                'name'=>'Chicken',
                'price'=>'200',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m2.jpg',
            ],
            //BEVERAGES-----------------------------------------------------------------------------
            [
                'name'=>'Nescafe',
                'price'=>'250',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Cafane will reduce your stress. ',
                'gallery'=>'/images/be1.jpg',
            ],
            [
                'name'=>'Kool',
                'price'=>'50',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Amul Kool is Now in Bangladesh. ',
                'gallery'=>'/images/be2.jpg',
            ],
            [
                'name'=>'Tang',
                'price'=>'950',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Original mango flavour. ',
                'gallery'=>'/images/be3.jpg',
            ],
            [
                'name'=>'Roof Afza',
                'price'=>'110',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'From Pakistan. ',
                'gallery'=>'/images/be4.jpg',
            ],
            [
                'name'=>'TRU',
                'price'=>'750',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Have every drop in soul with TRU. ',
                'gallery'=>'/images/be5.jpg',
            ],
            [
                'name'=>'Mr Twist',
                'price'=>'10',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Feel the notalgic. ',
                'gallery'=>'/images/be6.jpg',
            ],
            //CHLOTH-----------------------------------------------------------------------------
            [
                'name'=>'Gucci',
                'price'=>'150',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment.jpg',
            ],
            [
                'name'=>'Lose Pants',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp1.jpg',
            ],
            [
                'name'=>'Jacket',
                'price'=>'800',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment1.jpg',
            ],
            [
                'name'=>'Trouser',
                'price'=>'400',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp2.jpg',
            ],
            [
                'name'=>'DHAKA',
                'price'=>'100',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment2.jpg',
            ],
            [
                'name'=>'Denim',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment3.jpg',
            ],
            //SHOE -----------------------------------------------------------------------------
            [
                'name'=>'Shoe',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens1.jpeg',
            ],
            [
                'name'=>'Snecker',
                'price'=>'1800',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens2.jpg',
            ],
            [
                'name'=>'Sandle',
                'price'=>'3200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens3.jpg',
            ],
            //WOMEN TOP-----------------------------------------------------------------------------
            [
                'name'=>'Velvet Top',
                'price'=>'900',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt1.jpg',
            ],
            [
                'name'=>'Blue Top',
                'price'=>'700',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt2.jpg',
            ],
            [
                'name'=>'Velvet Top',
                'price'=>'500',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt3.jpg',
            ],
            //WOMEN HEEL-----------------------------------------------------------------------------
            [
                'name'=>'Pink Heel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel1.jpg',
            ],
            [
                'name'=>'Red Heel',
                'price'=>'5000',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel2.jpg',
            ],
            [
                'name'=>'Flat Sandel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel3.jpg',
            ],
            //BEAUTY-----------------------------------------------------------------------------
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b1.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b2.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b3.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b4.jpg',
            ],
            //Accessories-----------------------------------------------------------------------------
            [
                'name'=>'Guess (Gold Edition)',
                'price'=>'15000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a1.jpg',
            ],
            [
                'name'=>'Lather Walted',
                'price'=>'500',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a2.jpg',
            ],
            [
                'name'=>'Gucci Leo Ring',
                'price'=>'1000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Gucci limited edition grab yours now. ',
                'gallery'=>'/images/a3.jpg',
            ],
            [
                'name'=>'Side bag',
                'price'=>'670',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Strong side bag for daily work. ',
                'gallery'=>'/images/a4.jpg',
            ],
            [
                'name'=>'Grass necklace',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This necklace will enhance your look. ',
                'gallery'=>'/images/a5.jpg',
            ],// HYGIENE------------------------- -----------------------------------------------
            [
                'name'=>'Wave Air Freshner',
                'price'=>'210',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti tobacco',
                'gallery'=>'/images/hy1.jpg',
            ],
            [
                'name'=>'KN 95',
                'price'=>'40',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti Corona',
                'gallery'=>'\images\hy2.PNG',
            ],
            [
                'name'=>'Savlon Pro',
                'price'=>'200',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Best daily life cleaner',
                'gallery'=>'/images/hy3.jpg',
            ],
            // TREE------------------------- -----------------------------------------------
            [
                'name'=>'Bonzai',
                'price'=>'1500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr1.jpg',
            ],
            [
                'name'=>'Bonzai Lumb',
                'price'=>'700',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr2.jpg',
            ],
            [
                'name'=>'Cactus Gold',
                'price'=>'400',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr3.jpg',
            ],
            [
                'name'=>'Mini Cactus',
                'price'=>'500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr4.jpg',
            ],
            [
                'name'=>'Monstera',
                'price'=>'900',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr5.jpg',
            ],
            // Furnitures ------------------------- -----------------------------------------------
            [
                'name'=>'Dark Tul',
                'price'=>'1300',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f1.jpg',
            ],
            [
                'name'=>'Sofa Set',
                'price'=>'20000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f2.jpg',
            ],
            [
                'name'=>'Green Sofa',
                'price'=>'15000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f3.jpg',
            ],
            [
                'name'=>'Pinkish',
                'price'=>'2000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f4.jpg',
            ],
            [
                'name'=>'Desk Chair',
                'price'=>'5000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f5.jpg',
            ],
            //DIAPERS-----------------------------------------------------------------------------
            [
                'name'=>'Molfix',
                'price'=>'500',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 12 piece',
                'gallery'=>'/images/d1.jpg',
            ],
            [
                'name'=>'Huggies',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 32 piece',
                'gallery'=>'/images/d2.jpg',
            ],
            [
                'name'=>'Supermom',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 22 piece',
                'gallery'=>'/images/d3.jpg',
            ],
            [
                'name'=>'Avonee',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 10 piece',
                'gallery'=>'/images/d4.jpg',
            ],
            //FEEDER-----------------------------------------------------------------------------
            [
                'name'=>'Feeder 1.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe1.jpg',
            ],
            [
                'name'=>'Feeder 2.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe2.jpg',
            ],
            [
                'name'=>'Feeder 3.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe3.jpg',
            ],
            //MEAT-----------------------------------------------------------------------------

            [
                'name'=>'Mutton',
                'price'=>'800',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m1.jpg',
            ],
            [
                'name'=>'Chicken',
                'price'=>'200',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m2.jpg',
            ],
            //BEVERAGES-----------------------------------------------------------------------------
            [
                'name'=>'Nescafe',
                'price'=>'250',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Cafane will reduce your stress. ',
                'gallery'=>'/images/be1.jpg',
            ],
            [
                'name'=>'Kool',
                'price'=>'50',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Amul Kool is Now in Bangladesh. ',
                'gallery'=>'/images/be2.jpg',
            ],
            [
                'name'=>'Tang',
                'price'=>'950',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Original mango flavour. ',
                'gallery'=>'/images/be3.jpg',
            ],
            [
                'name'=>'Roof Afza',
                'price'=>'110',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'From Pakistan. ',
                'gallery'=>'/images/be4.jpg',
            ],
            [
                'name'=>'TRU',
                'price'=>'750',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Have every drop in soul with TRU. ',
                'gallery'=>'/images/be5.jpg',
            ],
            [
                'name'=>'Mr Twist',
                'price'=>'10',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Feel the notalgic. ',
                'gallery'=>'/images/be6.jpg',
            ],
            //CHLOTH-----------------------------------------------------------------------------
            [
                'name'=>'Gucci',
                'price'=>'150',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment.jpg',
            ],
            [
                'name'=>'Lose Pants',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp1.jpg',
            ],
            [
                'name'=>'Jacket',
                'price'=>'800',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment1.jpg',
            ],
            [
                'name'=>'Trouser',
                'price'=>'400',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp2.jpg',
            ],
            [
                'name'=>'DHAKA',
                'price'=>'100',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment2.jpg',
            ],
            [
                'name'=>'Denim',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment3.jpg',
            ],
            //SHOE -----------------------------------------------------------------------------
            [
                'name'=>'Shoe',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens1.jpeg',
            ],
            [
                'name'=>'Snecker',
                'price'=>'1800',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens2.jpg',
            ],
            [
                'name'=>'Sandle',
                'price'=>'3200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens3.jpg',
            ],
            //WOMEN TOP-----------------------------------------------------------------------------
            [
                'name'=>'Velvet Top',
                'price'=>'900',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt1.jpg',
            ],
            [
                'name'=>'Blue Top',
                'price'=>'700',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt2.jpg',
            ],
            [
                'name'=>'Velvet Top',
                'price'=>'500',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt3.jpg',
            ],
            //WOMEN HEEL-----------------------------------------------------------------------------
            [
                'name'=>'Pink Heel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel1.jpg',
            ],
            [
                'name'=>'Red Heel',
                'price'=>'5000',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel2.jpg',
            ],
            [
                'name'=>'Flat Sandel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel3.jpg',
            ],
            //BEAUTY-----------------------------------------------------------------------------
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b1.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b2.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b3.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b4.jpg',
            ],
            //Accessories-----------------------------------------------------------------------------
            [
                'name'=>'Guess (Gold Edition)',
                'price'=>'15000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a1.jpg',
            ],
            [
                'name'=>'Lather Walted',
                'price'=>'500',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a2.jpg',
            ],
            [
                'name'=>'Gucci Leo Ring',
                'price'=>'1000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Gucci limited edition grab yours now. ',
                'gallery'=>'/images/a3.jpg',
            ],
            [
                'name'=>'Side bag',
                'price'=>'670',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Strong side bag for daily work. ',
                'gallery'=>'/images/a4.jpg',
            ],
            [
                'name'=>'Grass necklace',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This necklace will enhance your look. ',
                'gallery'=>'/images/a5.jpg',
            ],// HYGIENE------------------------- -----------------------------------------------
            [
                'name'=>'Wave Air Freshner',
                'price'=>'210',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti tobacco',
                'gallery'=>'/images/hy1.jpg',
            ],
            [
                'name'=>'KN 95',
                'price'=>'40',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Anti Corona',
                'gallery'=>'\images\hy2.PNG',
            ],
            [
                'name'=>'Savlon Pro',
                'price'=>'200',
                'category1'=>'Home',
                'category2'=>'hygiene',
                'description'=>'Best daily life cleaner',
                'gallery'=>'/images/hy3.jpg',
            ],
            // TREE------------------------- -----------------------------------------------
            [
                'name'=>'Bonzai',
                'price'=>'1500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr1.jpg',
            ],
            [
                'name'=>'Bonzai Lumb',
                'price'=>'700',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr2.jpg',
            ],
            [
                'name'=>'Cactus Gold',
                'price'=>'400',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr3.jpg',
            ],
            [
                'name'=>'Mini Cactus',
                'price'=>'500',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr4.jpg',
            ],
            [
                'name'=>'Monstera',
                'price'=>'900',
                'category1'=>'Home',
                'category2'=>'Trees',
                'description'=>'Who doesnt love a bit of nature',
                'gallery'=>'/images/tr5.jpg',
            ],
            // Furnitures ------------------------- -----------------------------------------------
            [
                'name'=>'Dark Tul',
                'price'=>'1300',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f1.jpg',
            ],
            [
                'name'=>'Sofa Set',
                'price'=>'20000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f2.jpg',
            ],
            [
                'name'=>'Green Sofa',
                'price'=>'15000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f3.jpg',
            ],
            [
                'name'=>'Pinkish',
                'price'=>'2000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f4.jpg',
            ],
            [
                'name'=>'Desk Chair',
                'price'=>'5000',
                'category1'=>'Home',
                'category2'=>'Furnitures',
                'description'=>'Best minimal furniture choise for you',
                'gallery'=>'/images/f5.jpg',
            ],
            //DIAPERS-----------------------------------------------------------------------------
            [
                'name'=>'Molfix',
                'price'=>'500',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 12 piece',
                'gallery'=>'/images/d1.jpg',
            ],
            [
                'name'=>'Huggies',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 32 piece',
                'gallery'=>'/images/d2.jpg',
            ],
            [
                'name'=>'Supermom',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 22 piece',
                'gallery'=>'/images/d3.jpg',
            ],
            [
                'name'=>'Avonee',
                'price'=>'700',
                'category1'=>'Baby',
                'category2'=>'Diapers',
                'description'=>'M size , 10 piece',
                'gallery'=>'/images/d4.jpg',
            ],
            //FEEDER-----------------------------------------------------------------------------
            [
                'name'=>'Feeder 1.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe1.jpg',
            ],
            [
                'name'=>'Feeder 2.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe2.jpg',
            ],
            [
                'name'=>'Feeder 3.0',
                'price'=>'200',
                'category1'=>'Baby',
                'category2'=>'Feeders',
                'description'=>'Baby Feeders for your baby ',
                'gallery'=>'/images/fe3.jpg',
            ],
            //MEAT-----------------------------------------------------------------------------

            [
                'name'=>'Mutton',
                'price'=>'800',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m1.jpg',
            ],
            [
                'name'=>'Chicken',
                'price'=>'200',
                'category1'=>'Food',
                'category2'=>'Meats',
                'description'=>'Fresh frozen meat for you.',
                'gallery'=>'/images/m2.jpg',
            ],
            //BEVERAGES-----------------------------------------------------------------------------
            [
                'name'=>'Nescafe',
                'price'=>'250',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Cafane will reduce your stress. ',
                'gallery'=>'/images/be1.jpg',
            ],
            [
                'name'=>'Kool',
                'price'=>'50',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Amul Kool is Now in Bangladesh. ',
                'gallery'=>'/images/be2.jpg',
            ],
            [
                'name'=>'Tang',
                'price'=>'950',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Original mango flavour. ',
                'gallery'=>'/images/be3.jpg',
            ],
            [
                'name'=>'Roof Afza',
                'price'=>'110',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'From Pakistan. ',
                'gallery'=>'/images/be4.jpg',
            ],
            [
                'name'=>'TRU',
                'price'=>'750',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Have every drop in soul with TRU. ',
                'gallery'=>'/images/be5.jpg',
            ],
            [
                'name'=>'Mr Twist',
                'price'=>'10',
                'category1'=>'Food',
                'category2'=>'Beverages',
                'description'=>'Feel the notalgic. ',
                'gallery'=>'/images/be6.jpg',
            ],
            //CHLOTH-----------------------------------------------------------------------------
            [
                'name'=>'Gucci',
                'price'=>'150',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment.jpg',
            ],
            [
                'name'=>'Lose Pants',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp1.jpg',
            ],
            [
                'name'=>'Jacket',
                'price'=>'800',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment1.jpg',
            ],
            [
                'name'=>'Trouser',
                'price'=>'400',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/menp2.jpg',
            ],
            [
                'name'=>'DHAKA',
                'price'=>'100',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment2.jpg',
            ],
            [
                'name'=>'Denim',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Clothings',
                'description'=>'Best fitting for you ',
                'gallery'=>'/images/ment3.jpg',
            ],
            //SHOE -----------------------------------------------------------------------------
            [
                'name'=>'Shoe',
                'price'=>'1200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens1.jpeg',
            ],
            [
                'name'=>'Snecker',
                'price'=>'1800',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens2.jpg',
            ],
            [
                'name'=>'Sandle',
                'price'=>'3200',
                'category1'=>'MFashion',
                'category2'=>'Shoes',
                'description'=>'Best shoe for your daily work. ',
                'gallery'=>'/images/mens3.jpg',
            ],
            //WOMEN TOP-----------------------------------------------------------------------------
            [
                'name'=>'Velvet Top',
                'price'=>'900',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt1.jpg',
            ],
            [
                'name'=>'Blue Top',
                'price'=>'700',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt2.jpg',
            ],
            [
                'name'=>'Velvet Top',
                'price'=>'500',
                'category1'=>'WFashion',
                'category2'=>'Tops',
                'description'=>'Best cloth for you. ',
                'gallery'=>'/images/womt3.jpg',
            ],
            //WOMEN HEEL-----------------------------------------------------------------------------
            [
                'name'=>'Pink Heel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel1.jpg',
            ],
            [
                'name'=>'Red Heel',
                'price'=>'5000',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel2.jpg',
            ],
            [
                'name'=>'Flat Sandel',
                'price'=>'1400',
                'category1'=>'WFashion',
                'category2'=>'Heels',
                'description'=>'Best Heels on sales. ',
                'gallery'=>'/images/hel3.jpg',
            ],
            //BEAUTY-----------------------------------------------------------------------------
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b1.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b2.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b3.jpg',
            ],
            [
                'name'=>'Red Velvet',
                'price'=>'800',
                'category1'=>'WFashion',
                'category2'=>'Beauty & Health',
                'description'=>'Authentic beauty Product. ',
                'gallery'=>'/images/b4.jpg',
            ],
            //Accessories-----------------------------------------------------------------------------
            [
                'name'=>'Guess (Gold Edition)',
                'price'=>'15000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a1.jpg',
            ],
            [
                'name'=>'Lather Walted',
                'price'=>'500',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This watch will enhance your look. ',
                'gallery'=>'/images/a2.jpg',
            ],
            [
                'name'=>'Gucci Leo Ring',
                'price'=>'1000',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Gucci limited edition grab yours now. ',
                'gallery'=>'/images/a3.jpg',
            ],
            [
                'name'=>'Side bag',
                'price'=>'670',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'Strong side bag for daily work. ',
                'gallery'=>'/images/a4.jpg',
            ],
            [
                'name'=>'Grass necklace',
                'price'=>'700',
                'category1'=>'MFashion',
                'category2'=>'Accessories',
                'description'=>'This necklace will enhance your look. ',
                'gallery'=>'/images/a5.jpg',
            ],
        ]);
    }
}
